name: dart_table
description: Flutter data table with selection, sorting, filtering, and pagination. Also supports split view.
version: 0.0.1
homepage: https://mohesu.com
repository: https://github.com/mohesu/dart_table
issue_tracker: https://github.com/mohesu/dart_table/issues
screenshots:
  - description: "Table"
    path: assets/IMG_1.png
  - description: "Table with selection"
    path: assets/IMG_0.png

topics:
  - flutter-datagrid
  - flutter-table
  - data-table
  - datagrid
  - table

environment:
  sdk: ">=3.1.3 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  split_view: ^3.2.1
  syncfusion_flutter_datagrid: ^23.1.43

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter: null
